### ISSUE TITLE
deux cibles html dans le Makefile

### ISSUE THREAD

**Issue by burnol-math** [labopp/docinfo-sphinx#1]
Le Make file contient

```
.PHONY: html
html:
	$(SPHINXBUILD) -b html $(ALLSPHINXOPTS) $(BUILDDIR)/html
	@echo
	@echo "Build finished. The HTML pages are in $(BUILDDIR)/html."

.PHONY: livehtml
html:
	sphinx-autobuild -b html $(ALLSPHINXOPTS) $(BUILDDIR)/html
	@echo
	@echo "Live build finished. The HTML pages are in $(BUILDDIR)/html."
```

ce qui déclenche une erreur:

```
$ make html
Makefile:59: attention : écrasement des commandes pour la cible « html »
Makefile:53: attention : anciennes commandes ignorées pour la cible « html »
sphinx-autobuild -b html -d build/doctrees   source build/html
make: sphinx-autobuild : commande introuvable
make: *** [html] Erreur 127
```

La cible après ``.PHONY: livehtml`` ne devrait-elle pas être nommée ``livehtml`` ?

**Comment by burnol-math** [comment]
j'aurais dû dire un "avertissement"; l'erreur vient du fait que je n'ai pas ``sphinx-autobuild.py`` dans mon installation de Sphinx (j'utilise ici celle de la distribution Anaconda de Python, pas mon fork du Sphinx en développement).

**Comment by ktzanev** [comment]
J'utilise normalement le bat. 
Est-ce ok maintenant ?

**Comment by burnol-math** [comment]
Thanks for the amazingly quick fix! this is great support for my project!
