### ISSUE TITLE
les hyperliens devraient utiliser un seul tiret-bas

### ISSUE THREAD

**Issue by ghost** [labopp/docinfo-sphinx#1]
Dans calcul_examples.rst par exemple on trouve plusieurs liens du type ``foo <lien>`__` mais l'emploi de `__` est pour les liens « anonymes » (http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#anonymous-hyperlinks).

**Comment by ktzanev** [comment]
Je suis d'accord. C'est le pandoc qui a fais ça :(
J'ai corrigé un certain nombre, mais pas tous.

**Comment by ghost** [comment]
je vais corriger le reste ce soir.

**Comment by ghost** [comment]
Il reste un cas litigieux avec en calcul_jobs.rst ligne 78. Faudrait utiliser `:ref:`.

**Comment by ktzanev** [comment]
C'est fait pour le `:ref:` manquant.

**Comment by ghost** [comment]
+1
