### ISSUE TITLE
Quelques problèmes de formatage en sortie LaTeX

### ISSUE THREAD

**Issue by ghost** [labopp/docinfo-sphinx#10]
Pour mémoire
- les longues lignes dans les code-block ne sont gérées qu'à partir de Sphinx-1.4.2, (concerne entre autres calcul_examples.rst)
- il y a des positionnements d'images à améliorer par exemple dans impression_linux.rst,
- dans la table de impression_localisation.rst les numéros IP débordent. Problème difficile à régler car Sphinx calcule les colonnes de manière proportionnelle (package tabulary) mais les numéros IP ne peuvent pas passer à la ligne.

**Comment by ghost** [comment]
c'est un peu sévère "bug" ;-) 

Je rajoute un item
- les encadrés style "Note" sont beaucoup mieux rendus à partir de Sphinx-1.4.2 (ou 1.4.3 j'ai oublié). Avec 1.4.1, le filet horizontal du bas touche les lettres, entre autres problèmes.

Aussi à partir d'un certaine version de Sphinx 1.4.x, les encadrés des code-blocks ne prennent plus toute la largeur de page mais s'adaptent à la liste dans laquelle ils sont (même à plusieurs niveaux) ou au "quote".

**Comment by ktzanev** [comment]
J'imagine que tu parles de la sortie LaTeX ? Mais c'est pas toi le boss qui décide du style ?

**Comment by ghost** [comment]
oui oui  je ne parle que de sortie LaTeX. C'est difficile de supporter des "styles" en LaTeX, mais justement avec 1.4.5 et 1.5 ça deviendra plus simple car les macros et environnements ont des noms publics ou des variabls de customisation (couleurs, dimensions..) mais ça ne sera jamais du CSS.

**Comment by ktzanev** [comment]
Ça suffira pour nos petits besoins ;)

**Comment by ghost** [comment]
cf 7a747eb par @ktzanev qui a pour l'essentiel réglé le problème de la table des imprimantes

**Comment by ghost** [comment]
cf e092c71 pour le positionnement des images.

**Comment by ghost** [comment]
cf 50c1344 et 42ad567 qui forcent l'emploi de Sphinx 1.4.4 (au moins) par RTD ce qui règle les autres problèmes.

Memo: dès que celui-ci sera disponible via pip on forcera l'emploi de Sphinx 1.4.5 au moins car 1.4.4 a un bug pénible avec les inline codes (cf 1454d66 et d3a06b0 qui pourra être donc reverted).

Memo: contrôler pour les images lorsqu'on en sera à Sphinx 1.5.

Sur ce, ce ticket peut donc être fermé.

**Comment by ghost** [comment]
j'ai oublié de documenter ici que pour la sortie LaTeX, à partir du 1.4.5 les images seront correctement positionnées dans les listes et obéiront les environnements "quote". Pour le moment c'est pas idéal, mais c'est parce que Sphinx a un bug pour les inclusions d'image en LaTeX qui ne sera réglé qu'à partir de la 1.4.5.
